# This is an extra external service to allow users to access Prometheus query analyser externally on port 9100
apiVersion: v1
kind: Service
metadata:
  name: prometheus-prometheus-oper-prometheus-external
  namespace: prometheus
spec:
  ports:
  - name: web
    port: 9090
  selector:
    app: prometheus
    prometheus: prometheus-prometheus-oper-prometheus
  type: LoadBalancer
